<a href="https://colab.research.google.com/github/youngwiez/colab_python/blob/main/Raka_MPP_22Feb24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Array
---
Suatu tabel yang biasanya berisi angka bertipe sama
dan diindeks dalam bentuk tuple.

# Cara membuat array Numpy

---
**1. Menggunakan function `numpy.empty`**

Function `numpy.empty` mengembalikan nilai pada array dengan random values

Contoh command: `numpy.empty(shape, dtype=float, order='C')`

Keterangan:
*   `shape` = jumlah baris
*   `dtype` = tipe datanya (default-nya bertipe float)
*   `order` = `C` / `C_contiguous` (data urut dari terbesar) atau `F` / `F_contiguous` (dari terkecil)

In [1]:
import numpy as np

b = np.empty(2, dtype = int)
print("Matrix b : \n", b)

a = np.empty([2, 2], dtype = int)
print("\nMatrix a : \n", a)

c = np.empty([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [-4611686018427387904      140733732257791]

Matrix a : 
 [[97217233818429              0]
 [             0              0]]

Matrix c : 
 [[4.80316951e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


**2. Menggunakan function `numpy.zeros`**

Function `numpy.zeros` mengembalikan nilai pada array dengan 0

Contoh command: `numpy.zeros(shape, dtype=None, order='C')`

In [16]:
"""
Cara lain membuat array Numpy bisa dengan function numpy.zeros
Function numpy.zeros mengembalikan nilai array dengan 0

Contoh command: numpy.zeros(shape, dtype=None, order='C')
"""
import numpy as np

b = np.zeros(2, dtype = int)
print("Matrix b : \n", b)

a = np.zeros([2, 2], dtype = int)
print("\nMatrix a : \n", a)

c = np.zeros([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Operasi Aritmatika Numpy


---
**1. Penjumlahan**

In [17]:
import numpy as np

# Define kedua matrix untuk dijumlahkan
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Operasi penjumlahan matrix manual -> a+b
add_ans = a+b
print(add_ans)

# Operasi penjumlahan dengan function Numpy -> np.add(a,b)
add_ans = np.add(a, b)
print(add_ans)

# Fungsi dan operasi yang sama dapat digunakan untuk matrix lainnya
c = np.array([1, 2, 3, 4])
add_ans = a+b+c
print(add_ans)

add_ans = np.add(a, b, c)
print(add_ans)

[  7  77  23 130]
[  7  77  23 130]
[  8  79  26 134]
[  7  77  23 130]


**2. Pengurangan**

In [19]:
import numpy as np

# Define kedua matrix untuk dikurangkan
a = np.array([5, 72, 13, 100])
b = np.array([2, 5, 10, 30])

# Operasi penjumlahan matrix manual -> a+b
sub_ans = a-b
print(sub_ans)

# Operasi penjumlahan matrix dengan function numpy -> np.subtract(a,b)
sub_ans = np.subtract(a,b)
print(sub_ans)

c = np.array([1, 2, 3, 4])
sub_ans = a-b-c
print(sub_ans)

sub_ans = np.subtract(a, b, c)
print(sub_ans)

[ 3 67  3 70]
[ 3 67  3 70]
[ 2 65  0 66]
[ 3 67  3 70]
