<a href="https://colab.research.google.com/github/youngwiez/colab_python/blob/main/Raka_MPP_22Feb24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Time Series Analysis


---
Digunakan untuk melihat pergerakan/tren suatu data berdasarkan pola waktu. Visualisasi time series analysis ini menggunakan beberapa library, salah satunya library **Numpy**.

# Numpy Array
---
Suatu tabel yang biasanya berisi angka bertipe sama
dan diindeks dalam bentuk tuple.
Untuk Time Series Analysis, Numpy berfungsi untuk melakukan perhitungan matematika numerik dan menangani array multidimensi

# Cara membuat array Numpy

---
**1. Menggunakan function `numpy.empty`**

Function `numpy.empty` mengembalikan nilai pada array dengan random values

Contoh command: `numpy.empty(shape, dtype=float, order='C')`

Keterangan:
*   `shape` = jumlah baris
*   `dtype` = tipe datanya (default-nya bertipe float)
*   `order` = `C` / `C_contiguous` (data urut dari terbesar) atau `F` / `F_contiguous` (dari terkecil)

In [1]:
import numpy as np

b = np.empty(2, dtype = int)
print("Matrix b : \n", b)

a = np.empty([2, 2], dtype = int)
print("\nMatrix a : \n", a)

c = np.empty([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [-4611686018427387904      140733732257791]

Matrix a : 
 [[97217233818429              0]
 [             0              0]]

Matrix c : 
 [[4.80316951e-310 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 0.00000000e+000]]


**2. Menggunakan function `numpy.zeros`**

Function `numpy.zeros` mengembalikan nilai pada array dengan 0

Contoh command: `numpy.zeros(shape, dtype=None, order='C')`

In [16]:
"""
Cara lain membuat array Numpy bisa dengan function numpy.zeros
Function numpy.zeros mengembalikan nilai array dengan 0

Contoh command: numpy.zeros(shape, dtype=None, order='C')
"""
import numpy as np

b = np.zeros(2, dtype = int)
print("Matrix b : \n", b)

a = np.zeros([2, 2], dtype = int)
print("\nMatrix a : \n", a)

c = np.zeros([3, 3])
print("\nMatrix c : \n", c)

Matrix b : 
 [0 0]

Matrix a : 
 [[0 0]
 [0 0]]

Matrix c : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Contoh Penggunaan Numpy Array untuk Visualiasai Time Series Analysis


---

In [23]:
#import library yang diperlukan
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf
from statsmodels.tsa.stattools import adfuller

# membaca csv
df = pd.read_csv("stock_data.csv",
                 parse_dates=True,
                 index_col="Date")

# menampilkan 5 baris pertama dataset
df.head()

Unnamed: 0   Open   High    Low  Close    Volume  Name
Date                                                              
2006-01-03         NaN  39.69  41.22  38.79  40.91  24232729  AABA
2006-01-04         NaN  41.22  41.90  40.77  40.97  20553479  AABA
2006-01-05         NaN  40.93  41.73  40.85  41.53  12829610  AABA
2006-01-06         NaN  42.88  43.57  42.80  43.21  29422828  AABA
2006-01-09         NaN  43.10  43.66  42.82  43.42  16268338  AABA